apiVersion: v1
kind: Service
metadata:
  name: ltphuongduy-devops-capstone-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: ltphuongduy-devops-capstone
      protocol: TCP
  selector:
    app: ltphuongduy-devops-capstone